### ISSUE TITLE
¿Convertir está utilidad en un paquete composer?

### ISSUE THREAD

**Issue by cesargb** [Laraveles/spanish#15]
Muy buena la aportación, pienso que sería muy interesante construir estás traducciones en un paquete composer para que su instalación sea más sencilla.

Yo mismo podría colaborar en el desarrollo e iniciarlo.

Soló faltaría definir el nombre del paquete, quizás ¿`Laraveles/spanish`? y si sería mejor crear un nuevo proyecto en github o reescribir este.

Estamos en contacto!

**Comment by IsraelOrtuno** [comment]
Estaría genial. Sinceramente creo que se podría trabajar directamente sobre este, pues quien lo utiliza directamente lo clona. Lo podría registrar como `laraveles/spanish`.

Sería genial ese aporte @cesargb

**Comment by cesargb** [comment]
@IsraelOrtuno Cuando tenga algo hago realizo un PR

**Comment by cesargb** [comment]
@IsraelOrtuno Ya he subido un PR con el paquete para laravel. https://github.com/Laraveles/lang-spanish/pull/16

Yo antes de realizar el merge, realizaría un branch nuevo con todo lo que hay ahora, por si alguien quiere instalarlo con el método convencional.

El siguiente paso sería crearse una cuenta en https://packagist.org/, yo tengo una, pero imagino que es mejor crear a partir de una cuenta genérica. Así podremos publicarlo en composer y probar una instalación en laravel 5.4 y 5.5 antes de crear la primera versión :)

Cualquier cambio que estimes oportuno, ... no hay ningún problema.

**Comment by IsraelOrtuno** [comment]
Se hizo el merge, qué tal ahora mejorarlo para en lugar de un comando utilizar directamente `vendor:publish`

**Comment by IsraelOrtuno** [comment]
No vi que ya lo hacía, lo especifiqué en la doc ;)
