### ISSUE TITLE
Ortografía en las notificaciones por email

### ISSUE THREAD

**Issue by marcesdan** [Laraveles/spanish#36]
Hola, gracias por la gran traducción que han hecho!

Sin embargo, al final del mail, cuando dice "Si tienes problemas haciendo click en el botón "acción", copia y pega el siguiente **enlaenlace** en tu navegador", debería decir **enlace**

Saludos!

**Comment by marcesdan** [comment]
Mmm, podría aprender

**Comment by IsraelOrtuno** [comment]
#37
