### ISSUE TITLE
[Pregunta] ¿Sirve para Laravel 6.x?

### ISSUE THREAD

**Issue by guillermo7227** [Laraveles/spanish#56]
He usado este paquete en Laravel 5.8 pero ahora estoy manejando un proyecto con Laravel 6.

**Comment by IsraelOrtuno** [comment]
Si claro 👍

**Comment by n3storm** [comment]
Creo que @guillermo7227 pregunta porque en la descripción del proyecto aquí en github pone:

>  Repositorio de idioma de Laravel 5...
