### ISSUE TITLE
Laravel 7 - Cambio de clave

### ISSUE THREAD

**Issue by driade** [Laraveles/spanish#58]
Hola.

En Laravel 7 la clave

```
"If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser: [:actionURL](:actionURL)"
```

que se encuentra en es.json cambia a

```
"If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser: [:displayableActionUrl](:actionURL)"
```

¿Quizá sería interesante abrir una nueva versión (1.5.x?) para tener en ella las modificaciones especiales de Laravel 7?

Un saludo y gracias.

**Comment by IsraelOrtuno** [comment]
Podría hacer un pull request con el cambio? Ya vemos si damos un versionado u otro!

**Comment by driade** [comment]
Desafortunadamente parece que en la próxima release de Laravel van a volver a cambiarlo :(

https://github.com/laravel/framework/commits/7.x/src/Illuminate/Notifications/resources/views/email.blade.php

¿Cuál es su opinión?

**Comment by IsraelOrtuno** [comment]
En qué ha quedado esto al final @driade?

**Comment by driade** [comment]
Añado pul request

https://github.com/Laraveles/spanish/pull/60

Pues según leo en el thread, en cambio ha sido aceptado en 7.x y también en 6.x

En mi opinión, lo más "seguro" sería dejar la línea actual tal y como está

```
"If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser: [:actionURL](:actionURL)": "Si tienes problemas haciendo click en el botón \":actionText\", copia y pega el siguiente\nenlace en tu navegador: [:actionURL](:actionURL)",
```

Y añadir

```
"If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser:": "Si tienes problemas haciendo click en el botón \":actionText\", copia y pega el siguiente\nenlace en tu navegador:",
```

(https://github.com/laravel/framework/pull/32189/files)

**Comment by driade** [comment]
Ya que el pull ha sido mergeado, cierro el issue.
